<?php
// WebEx Time Zone Data
// Generated on 2015-03-17T00:01:16+01:00
// PHP version 5.3.15
// Timezone database version 2012.3
return array(
    0 => array(
        'timeZoneID'   => 0,
        'gmtOffset'    => 720,
        'description'  => 'Marshall Islands (Dateline Time, GMT+12:00)',
        'standardName' => 'Dateline Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Majuro',
    ),
    1 => array(
        'timeZoneID'   => 1,
        'gmtOffset'    => -660,
        'description'  => 'Samoa (Samoa Time, GMT-11:00)',
        'standardName' => 'Samoa Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Pago_Pago',
    ),
    2 => array(
        'timeZoneID'   => 2,
        'gmtOffset'    => -600,
        'description'  => 'Honolulu (Hawaii Time, GMT-10:00)',
        'standardName' => 'Hawaii Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Honolulu',
    ),
    3 => array(
        'timeZoneID'   => 3,
        'gmtOffset'    => -480,
        'description'  => 'Anchorage (Alaska Daylight Time, GMT-08:00)',
        'standardName' => '',
        'daylightName' => 'Alaska Daylight Time',
        'tzid'         => 'America/Anchorage',
    ),
    4 => array(
        'timeZoneID'   => 4,
        'gmtOffset'    => -420,
        'description'  => 'San Francisco (Pacific Daylight Time, GMT-07:00)',
        'standardName' => '',
        'daylightName' => 'Pacific Daylight Time',
        'tzid'         => 'America/Los_Angeles',
    ),
    5 => array(
        'timeZoneID'   => 5,
        'gmtOffset'    => -420,
        'description'  => 'Arizona (Mountain Time, GMT-07:00)',
        'standardName' => 'Mountain Time',
        'daylightName' => '',
        'tzid'         => 'America/Phoenix',
    ),
    6 => array(
        'timeZoneID'   => 6,
        'gmtOffset'    => -360,
        'description'  => 'Denver (Mountain Daylight Time, GMT-06:00)',
        'standardName' => '',
        'daylightName' => 'Mountain Daylight Time',
        'tzid'         => 'America/Denver',
    ),
    7 => array(
        'timeZoneID'   => 7,
        'gmtOffset'    => -300,
        'description'  => 'Chicago (Central Daylight Time, GMT-05:00)',
        'standardName' => '',
        'daylightName' => 'Central Daylight Time',
        'tzid'         => 'America/Chicago',
    ),
    8 => array(
        'timeZoneID'   => 8,
        'gmtOffset'    => -360,
        'description'  => 'Mexico City (Mexico Standard Time, GMT-06:00)',
        'standardName' => 'Mexico Standard Time',
        'daylightName' => '',
        'tzid'         => 'America/Mexico_City',
    ),
    9 => array(
        'timeZoneID'   => 9,
        'gmtOffset'    => -360,
        'description'  => 'Saskatchewan (Central Time, GMT-06:00)',
        'standardName' => 'Central Time',
        'daylightName' => '',
        'tzid'         => 'America/Regina',
    ),
    10 => array(
        'timeZoneID'   => 10,
        'gmtOffset'    => -300,
        'description'  => 'Bogota (S. America Pacific Time, GMT-05:00)',
        'standardName' => 'S. America Pacific Time',
        'daylightName' => '',
        'tzid'         => 'America/Bogota',
    ),
    11 => array(
        'timeZoneID'   => 11,
        'gmtOffset'    => -240,
        'description'  => 'New York (Eastern Daylight Time, GMT-04:00)',
        'standardName' => '',
        'daylightName' => 'Eastern Daylight Time',
        'tzid'         => 'America/New_York',
    ),
    12 => array(
        'timeZoneID'   => 12,
        'gmtOffset'    => -240,
        'description'  => 'Indiana (Eastern Daylight Time, GMT-04:00)',
        'standardName' => '',
        'daylightName' => 'Eastern Daylight Time',
        'tzid'         => 'America/Indianapolis',
    ),
    13 => array(
        'timeZoneID'   => 13,
        'gmtOffset'    => -180,
        'description'  => 'Halifax (Atlantic Daylight Time, GMT-03:00)',
        'standardName' => '',
        'daylightName' => 'Atlantic Daylight Time',
        'tzid'         => 'America/Halifax',
    ),
    14 => array(
        'timeZoneID'   => 14,
        'gmtOffset'    => -240,
        'description'  => 'La Paz (S. America Western Time, GMT-04:00)',
        'standardName' => 'S. America Western Time',
        'daylightName' => '',
        'tzid'         => 'America/La_Paz',
    ),
    15 => array(
        'timeZoneID'   => 15,
        'gmtOffset'    => -90,
        'description'  => 'Newfoundland (Newfoundland Daylight Time, GMT-02:30)',
        'standardName' => '',
        'daylightName' => 'Newfoundland Daylight Time',
        'tzid'         => 'America/St_Johns',
    ),
    16 => array(
        'timeZoneID'   => 16,
        'gmtOffset'    => -180,
        'description'  => 'Brasilia (S. America Eastern Standard Time, GMT-03:00)',
        'standardName' => 'S. America Eastern Standard Time',
        'daylightName' => '',
        'tzid'         => 'America/Sao_Paulo',
    ),
    17 => array(
        'timeZoneID'   => 17,
        'gmtOffset'    => -180,
        'description'  => 'Buenos Aires (S. America Eastern Time, GMT-03:00)',
        'standardName' => 'S. America Eastern Time',
        'daylightName' => '',
        'tzid'         => 'America/Argentina/Buenos_Aires',
    ),
    18 => array(
        'timeZoneID'   => 18,
        'gmtOffset'    => -120,
        'description'  => 'Mid-Atlantic (Mid-Atlantic Time, GMT-02:00)',
        'standardName' => 'Mid-Atlantic Time',
        'daylightName' => '',
        'tzid'         => 'Atlantic/South_Georgia',
    ),
    19 => array(
        'timeZoneID'   => 19,
        'gmtOffset'    => -60,
        'description'  => 'Azores (Azores Time, GMT-01:00)',
        'standardName' => 'Azores Time',
        'daylightName' => '',
        'tzid'         => 'Atlantic/Azores',
    ),
    20 => array(
        'timeZoneID'   => 20,
        'gmtOffset'    => 0,
        'description'  => 'Reykjavik (Greenwich Time, GMT)',
        'standardName' => 'Greenwich Time',
        'daylightName' => '',
        'tzid'         => 'Atlantic/Reykjavik',
    ),
    21 => array(
        'timeZoneID'   => 21,
        'gmtOffset'    => 0,
        'description'  => 'London (GMT Time, GMT)',
        'standardName' => 'GMT Time',
        'daylightName' => '',
        'tzid'         => 'Europe/London',
    ),
    22 => array(
        'timeZoneID'   => 22,
        'gmtOffset'    => 60,
        'description'  => 'Amsterdam (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Amsterdam',
    ),
    23 => array(
        'timeZoneID'   => 23,
        'gmtOffset'    => 60,
        'description'  => 'Paris (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Paris',
    ),
    25 => array(
        'timeZoneID'   => 25,
        'gmtOffset'    => 60,
        'description'  => 'Berlin (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Berlin',
    ),
    26 => array(
        'timeZoneID'   => 26,
        'gmtOffset'    => 120,
        'description'  => 'Athens (Greece Time, GMT+02:00)',
        'standardName' => 'Greece Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Athens',
    ),
    28 => array(
        'timeZoneID'   => 28,
        'gmtOffset'    => 120,
        'description'  => 'Cairo (Egypt Time, GMT+02:00)',
        'standardName' => 'Egypt Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Cairo',
    ),
    29 => array(
        'timeZoneID'   => 29,
        'gmtOffset'    => 120,
        'description'  => 'Pretoria (South Africa Time, GMT+02:00)',
        'standardName' => 'South Africa Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Johannesburg',
    ),
    30 => array(
        'timeZoneID'   => 30,
        'gmtOffset'    => 120,
        'description'  => 'Helsinki (Northern Europe Time, GMT+02:00)',
        'standardName' => 'Northern Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Helsinki',
    ),
    31 => array(
        'timeZoneID'   => 31,
        'gmtOffset'    => 120,
        'description'  => 'Tel Aviv (Israel Standard Time, GMT+02:00)',
        'standardName' => 'Israel Standard Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Jerusalem',
    ),
    32 => array(
        'timeZoneID'   => 32,
        'gmtOffset'    => 180,
        'description'  => 'Riyadh (Saudi Arabia Time, GMT+03:00)',
        'standardName' => 'Saudi Arabia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Riyadh',
    ),
    33 => array(
        'timeZoneID'   => 33,
        'gmtOffset'    => 180,
        'description'  => 'Moscow (Russian Time, GMT+03:00)',
        'standardName' => 'Russian Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Moscow',
    ),
    34 => array(
        'timeZoneID'   => 34,
        'gmtOffset'    => 180,
        'description'  => 'Nairobi (Nairobi Time, GMT+03:00)',
        'standardName' => 'Nairobi Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Nairobi',
    ),
    35 => array(
        'timeZoneID'   => 35,
        'gmtOffset'    => 210,
        'description'  => 'Tehran (Iran Standard Time, GMT+03:30)',
        'standardName' => 'Iran Standard Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Tehran',
    ),
    36 => array(
        'timeZoneID'   => 36,
        'gmtOffset'    => 240,
        'description'  => 'Abu Dhabi, Muscat (Arabian Time, GMT+04:00)',
        'standardName' => 'Arabian Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Muscat',
    ),
    37 => array(
        'timeZoneID'   => 37,
        'gmtOffset'    => 240,
        'description'  => 'Baku (Baku Standard Time, GMT+04:00)',
        'standardName' => 'Baku Standard Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Baku',
    ),
    38 => array(
        'timeZoneID'   => 38,
        'gmtOffset'    => 270,
        'description'  => 'Kabul (Afghanistan Time, GMT+04:30)',
        'standardName' => 'Afghanistan Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Kabul',
    ),
    39 => array(
        'timeZoneID'   => 39,
        'gmtOffset'    => 300,
        'description'  => 'Yekaterinburg (West Asia Time, GMT+05:00)',
        'standardName' => 'West Asia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Yekaterinburg',
    ),
    40 => array(
        'timeZoneID'   => 40,
        'gmtOffset'    => 300,
        'description'  => 'Islamabad (West Asia Time, GMT+05:00)',
        'standardName' => 'West Asia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Karachi',
    ),
    41 => array(
        'timeZoneID'   => 41,
        'gmtOffset'    => 330,
        'description'  => 'Mumbai (India Time, GMT+05:30)',
        'standardName' => 'India Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Kolkata',
    ),
    42 => array(
        'timeZoneID'   => 42,
        'gmtOffset'    => 330,
        'description'  => 'Colombo (Colombo Time, GMT+05:30)',
        'standardName' => 'Colombo Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Colombo',
    ),
    43 => array(
        'timeZoneID'   => 43,
        'gmtOffset'    => 360,
        'description'  => 'Almaty (Central Asia Time, GMT+06:00)',
        'standardName' => 'Central Asia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Almaty',
    ),
    44 => array(
        'timeZoneID'   => 44,
        'gmtOffset'    => 420,
        'description'  => 'Bangkok (Bangkok Time, GMT+07:00)',
        'standardName' => 'Bangkok Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Bangkok',
    ),
    45 => array(
        'timeZoneID'   => 45,
        'gmtOffset'    => 480,
        'description'  => 'Beijing (China Time, GMT+08:00)',
        'standardName' => 'China Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Shanghai',
    ),
    46 => array(
        'timeZoneID'   => 46,
        'gmtOffset'    => 480,
        'description'  => 'Perth (Australia Western Time, GMT+08:00)',
        'standardName' => 'Australia Western Time',
        'daylightName' => '',
        'tzid'         => 'Australia/Perth',
    ),
    47 => array(
        'timeZoneID'   => 47,
        'gmtOffset'    => 480,
        'description'  => 'Singapore (Singapore Time, GMT+08:00)',
        'standardName' => 'Singapore Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Singapore',
    ),
    48 => array(
        'timeZoneID'   => 48,
        'gmtOffset'    => 480,
        'description'  => 'Taipei (Taipei Time, GMT+08:00)',
        'standardName' => 'Taipei Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Taipei',
    ),
    49 => array(
        'timeZoneID'   => 49,
        'gmtOffset'    => 540,
        'description'  => 'Tokyo (Japan Time, GMT+09:00)',
        'standardName' => 'Japan Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Tokyo',
    ),
    50 => array(
        'timeZoneID'   => 50,
        'gmtOffset'    => 540,
        'description'  => 'Seoul (Korea Time, GMT+09:00)',
        'standardName' => 'Korea Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Seoul',
    ),
    51 => array(
        'timeZoneID'   => 51,
        'gmtOffset'    => 540,
        'description'  => 'Yakutsk (Yakutsk Time, GMT+09:00)',
        'standardName' => 'Yakutsk Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Yakutsk',
    ),
    52 => array(
        'timeZoneID'   => 52,
        'gmtOffset'    => 630,
        'description'  => 'Adelaide (Australia Central Daylight Time, GMT+10:30)',
        'standardName' => '',
        'daylightName' => 'Australia Central Daylight Time',
        'tzid'         => 'Australia/Adelaide',
    ),
    53 => array(
        'timeZoneID'   => 53,
        'gmtOffset'    => 570,
        'description'  => 'Darwin (Australia Central Time, GMT+09:30)',
        'standardName' => 'Australia Central Time',
        'daylightName' => '',
        'tzid'         => 'Australia/Darwin',
    ),
    54 => array(
        'timeZoneID'   => 54,
        'gmtOffset'    => 600,
        'description'  => 'Brisbane (Australia Eastern Time, GMT+10:00)',
        'standardName' => 'Australia Eastern Time',
        'daylightName' => '',
        'tzid'         => 'Australia/Brisbane',
    ),
    55 => array(
        'timeZoneID'   => 55,
        'gmtOffset'    => 660,
        'description'  => 'Sydney (Australia Eastern Daylight Time, GMT+11:00)',
        'standardName' => '',
        'daylightName' => 'Australia Eastern Daylight Time',
        'tzid'         => 'Australia/Sydney',
    ),
    56 => array(
        'timeZoneID'   => 56,
        'gmtOffset'    => 600,
        'description'  => 'Guam (West Pacific Time, GMT+10:00)',
        'standardName' => 'West Pacific Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Guam',
    ),
    57 => array(
        'timeZoneID'   => 57,
        'gmtOffset'    => 660,
        'description'  => 'Hobart (Tasmania Daylight Time, GMT+11:00)',
        'standardName' => '',
        'daylightName' => 'Tasmania Daylight Time',
        'tzid'         => 'Australia/Hobart',
    ),
    58 => array(
        'timeZoneID'   => 58,
        'gmtOffset'    => 600,
        'description'  => 'Vladivostok (Vladivostok Time, GMT+10:00)',
        'standardName' => 'Vladivostok Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Vladivostok',
    ),
    59 => array(
        'timeZoneID'   => 59,
        'gmtOffset'    => 660,
        'description'  => 'Solomon Is (Central Pacific Time, GMT+11:00)',
        'standardName' => 'Central Pacific Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Guadalcanal',
    ),
    60 => array(
        'timeZoneID'   => 60,
        'gmtOffset'    => 780,
        'description'  => 'Wellington (New Zealand Daylight Time, GMT+13:00)',
        'standardName' => '',
        'daylightName' => 'New Zealand Daylight Time',
        'tzid'         => 'Pacific/Auckland',
    ),
    61 => array(
        'timeZoneID'   => 61,
        'gmtOffset'    => 720,
        'description'  => 'Fiji (Fiji Standard Time, GMT+12:00)',
        'standardName' => 'Fiji Standard Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Fiji',
    ),
    130 => array(
        'timeZoneID'   => 130,
        'gmtOffset'    => 60,
        'description'  => 'Stockholm (Sweden Time, GMT+01:00)',
        'standardName' => 'Sweden Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Stockholm',
    ),
    131 => array(
        'timeZoneID'   => 131,
        'gmtOffset'    => -420,
        'description'  => 'Tijuana (Mexico Pacific Daylight Time, GMT-07:00)',
        'standardName' => '',
        'daylightName' => 'Mexico Pacific Daylight Time',
        'tzid'         => 'America/Tijuana',
    ),
    132 => array(
        'timeZoneID'   => 132,
        'gmtOffset'    => -420,
        'description'  => 'Chihuahua (Mexico Mountain Standard Time, GMT-07:00)',
        'standardName' => 'Mexico Mountain Standard Time',
        'daylightName' => '',
        'tzid'         => 'America/Chihuahua',
    ),
    133 => array(
        'timeZoneID'   => 133,
        'gmtOffset'    => -210,
        'description'  => 'Caracas (S. America Western Time, GMT-04:30)',
        'standardName' => 'S. America Western Time',
        'daylightName' => '',
        'tzid'         => 'America/Caracas',
    ),
    134 => array(
        'timeZoneID'   => 134,
        'gmtOffset'    => 480,
        'description'  => 'Kuala Lumpur (Malaysia Time, GMT+08:00)',
        'standardName' => 'Malaysia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Kuala_Lumpur',
    ),
    135 => array(
        'timeZoneID'   => 135,
        'gmtOffset'    => -180,
        'description'  => 'Recife (S. America Eastern Time, GMT-03:00)',
        'standardName' => 'S. America Eastern Time',
        'daylightName' => '',
        'tzid'         => 'America/Recife',
    ),
    136 => array(
        'timeZoneID'   => 136,
        'gmtOffset'    => 0,
        'description'  => 'Casablanca (Morocco Standard Time, GMT)',
        'standardName' => 'Morocco Standard Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Casablanca',
    ),
    137 => array(
        'timeZoneID'   => 137,
        'gmtOffset'    => -360,
        'description'  => 'Tegucigalpa (Honduras Time, GMT-06:00)',
        'standardName' => 'Honduras Time',
        'daylightName' => '',
        'tzid'         => 'America/Tegucigalpa',
    ),
    138 => array(
        'timeZoneID'   => 138,
        'gmtOffset'    => -180,
        'description'  => 'Nuuk (Greenland Standard Time, GMT-03:00)',
        'standardName' => 'Greenland Standard Time',
        'daylightName' => '',
        'tzid'         => 'America/Godthab',
    ),
    139 => array(
        'timeZoneID'   => 139,
        'gmtOffset'    => 120,
        'description'  => 'Amman (Jordan Standard Time, GMT+02:00)',
        'standardName' => 'Jordan Standard Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Amman',
    ),
    140 => array(
        'timeZoneID'   => 140,
        'gmtOffset'    => 120,
        'description'  => 'Istanbul (Eastern Europe Time, GMT+02:00)',
        'standardName' => 'Eastern Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Istanbul',
    ),
    141 => array(
        'timeZoneID'   => 141,
        'gmtOffset'    => 345,
        'description'  => 'Kathmandu (Nepal Time, GMT+05:45)',
        'standardName' => 'Nepal Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Kathmandu',
    ),
    142 => array(
        'timeZoneID'   => 142,
        'gmtOffset'    => 60,
        'description'  => 'Rome (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Rome',
    ),
    143 => array(
        'timeZoneID'   => 143,
        'gmtOffset'    => 60,
        'description'  => 'West Africa (West Africa Time, GMT+01:00)',
        'standardName' => 'West Africa Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Lagos',
    ),
    144 => array(
        'timeZoneID'   => 144,
        'gmtOffset'    => 60,
        'description'  => 'Madrid (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Madrid',
    ),
    145 => array(
        'timeZoneID'   => 145,
        'gmtOffset'    => -240,
        'description'  => 'Santiago (S. America Western Standard Time, GMT-04:00)',
        'standardName' => 'S. America Western Standard Time',
        'daylightName' => '',
        'tzid'         => 'America/Santiago',
    ),
    146 => array(
        'timeZoneID'   => 146,
        'gmtOffset'    => -300,
        'description'  => 'Panama (Eastern Time, GMT-05:00)',
        'standardName' => 'Eastern Time',
        'daylightName' => '',
        'tzid'         => 'America/Panama',
    ),
    147 => array(
        'timeZoneID'   => 147,
        'gmtOffset'    => 60,
        'description'  => 'Brussels (Europe Time, GMT+01:00)',
        'standardName' => 'Europe Time',
        'daylightName' => '',
        'tzid'         => 'Europe/Brussels',
    ),
    148 => array(
        'timeZoneID'   => 148,
        'gmtOffset'    => -180,
        'description'  => 'Asuncion (Paraguay Summer Time, GMT-03:00)',
        'standardName' => 'Paraguay Summer Time',
        'daylightName' => '',
        'tzid'         => 'America/Asuncion',
    ),
    149 => array(
        'timeZoneID'   => 149,
        'gmtOffset'    => -180,
        'description'  => 'Montevideo (Uruguay Time, GMT-03:00)',
        'standardName' => 'Uruguay Time',
        'daylightName' => '',
        'tzid'         => 'America/Montevideo',
    ),
    150 => array(
        'timeZoneID'   => 150,
        'gmtOffset'    => -60,
        'description'  => 'Cape Verde (Cape Verde Time, GMT-01:00)',
        'standardName' => 'Cape Verde Time',
        'daylightName' => '',
        'tzid'         => 'Atlantic/Cape_Verde',
    ),
    151 => array(
        'timeZoneID'   => 151,
        'gmtOffset'    => 120,
        'description'  => 'Windhoek (West Africa Summer Time, GMT+02:00)',
        'standardName' => 'West Africa Summer Time',
        'daylightName' => '',
        'tzid'         => 'Africa/Windhoek',
    ),
    152 => array(
        'timeZoneID'   => 152,
        'gmtOffset'    => 390,
        'description'  => 'Yangon (Myanmar Time, GMT+06:30)',
        'standardName' => 'Myanmar Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Rangoon',
    ),
    153 => array(
        'timeZoneID'   => 153,
        'gmtOffset'    => 780,
        'description'  => 'Tonga (Tonga Time, GMT+13:00)',
        'standardName' => 'Tonga Time',
        'daylightName' => '',
        'tzid'         => 'Pacific/Tongatapu',
    ),
    154 => array(
        'timeZoneID'   => 154,
        'gmtOffset'    => 420,
        'description'  => 'Jakarta (Western Indonesia Time, GMT+07:00)',
        'standardName' => 'Western Indonesia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Jakarta',
    ),
    155 => array(
        'timeZoneID'   => 155,
        'gmtOffset'    => 240,
        'description'  => 'Yerevan (Armenia Time, GMT+04:00)',
        'standardName' => 'Armenia Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Yerevan',
    ),
    156 => array(
        'timeZoneID'   => 156,
        'gmtOffset'    => 360,
        'description'  => 'Novosibirsk (Novosibirsk Time, GMT+06:00)',
        'standardName' => 'Novosibirsk Time',
        'daylightName' => '',
        'tzid'         => 'Asia/Novosibirsk',
    ),
);
